//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int Admin_ID { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Lastname { get; set; }
        public string Admin_Mail { get; set; }
        public string Admin_Pass { get; set; }
    }
}
