//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.PURCHASE = new HashSet<PURCHASE>();
        }
    
        public int Book_ID { get; set; }
        public string Book_Name { get; set; }
        public Nullable<byte> Book_Category { get; set; }
        public Nullable<int> Book_Author { get; set; }
        public string Book_Year { get; set; }
        public string Book_Publisher { get; set; }
        public string Book_Page { get; set; }
        public Nullable<int> Book_Price { get; set; }
        public Nullable<bool> Book_Stocks { get; set; }
    
        public virtual AUTHORS AUTHORS { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE> PURCHASE { get; set; }
    }
}
