//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASE
    {
        public int Pr_ID { get; set; }
        public Nullable<int> Pr_Book { get; set; }
        public Nullable<int> Pr_User { get; set; }
        public Nullable<System.DateTime> Pr_Date { get; set; }
        public Nullable<int> Pr_Price { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
